language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

sudo: false

before_install:
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install

script:
  - composer --verbose update
